[package]
name = "persistence"
version = "0.1.0"
edition = "2024"

[dependencies]
common-utils = { path = "./../common-utils" }
acme-client = { path = "./../acme-client" }
sqlite = "0.37.0"
tracing = "0.1.44"