[package]
name = "common-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1.17.0", features = ["v4"] }
clap = { version = "4.5.60", features = ["derive"] }
tracing = "0.1.44"


[dev-dependencies]
tempfile = "3.20.0"